default: pos
pos:
	g++  par_circuit.cpp seq_circuit.cpp eval.cpp main.cpp -o opt_tfhe -ltfhe-spqlios-fma -fopenmp -DPOSITION

nopos:
	g++  par_circuit.cpp seq_circuit.cpp eval.cpp main.cpp -o opt_tfhe -ltfhe-spqlios-fma -fopenmp
